import os

# MQTT Broker configuration
MQTT_BROKER_ADRESS      = os.getenv('MQTT_BROKER_ADRESS', 'host.docker.internal')
MQTT_PORT               = int(os.getenv('MQTT_BROKER_PORT', 1883))

ROBOT_PACKAGE_FOLDER    = 'robot_package' # Directory with robot modules
SIMULATOR_BASE_TOPIC    = os.getenv('USER_ID', 'default_user')
TERMINAL_BASE_TOPIC     = 'TERMINAL'

# Default audio file extension.
AUDIO_EXTENSION = ".wav"

# Audio format generated by IBM Watson (file extension).
WATSON_AUDIO_EXTENSION = ".mp3"
ACCEPT_AUDIO_EXTENSION = "audio/mp3"
